version: '3.7'

services:

  backend:
    container_name: ${CONTAINER_NAME}
    hostname: ${CONTAINER_NAME}
    build: .
    image: ${IMAGE_FULL_NAME}
    env_file:
      - ./docker/mongodb/.env
      - ./docker/mongodb/MONGODB.variables
    ports:
      - "4000:4000"
    networks:
      - backend-net
      - frontend-net

networks:

  backend-net:
    external:
      name: ${BACKEND_NETWORK_NAME}

  frontend-net:
    external:
      name: ${FRONTEND_NETWORK_NAME}
