version: '3.7'

services:

  backend:
    container_name: ${CONTAINER_NAME}
    build: .
    image: ${IMAGE_FULL_NAME}
    ports:
      - "4000:4000"
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
    name: ${NETWORK_NAME}
