version: '3.7'

services:

  backend:
    container_name: ${CONTAINER_NAME}
    build: .
    image: ${IMAGE_FULL_NAME}
    ports:
      - "4000:4000"

networks:

  default:
    external:
      name: ${NETWORK_NAME}
